// This file has been autogenerated from a class added in the UI designer.

using System;
using Foundation;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using UIKit;
using WebRTC.AppRTC;

namespace WebRTC.iOS.Demo
{
    public partial class LoginViewController : UIViewController
    {
        private readonly LoginService _loginService = new LoginService();

        public LoginViewController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            
            JsonConvert.DefaultSettings = () =>
            {
                var settings = new JsonSerializerSettings();
                settings.NullValueHandling = NullValueHandling.Ignore;
                settings.Converters.Add(new StringEnumConverter());
                return settings;
            };

            Title = "Login";

            UsernameTextField.Text = "73367111";
            PasswordTextField.Text = "8112";

            LoginButton.TouchUpInside += LoginButtonOnTouchUpInside;
        }

        private async void LoginButtonOnTouchUpInside(object sender, EventArgs e)
        {
            LoadingContainer.Hidden = false;
            var token = await _loginService.LoginAsync(UsernameTextField.Text, PasswordTextField.Text);
            if (string.IsNullOrEmpty(token))
            {
                return;
            }
            
            LoadingContainer.Hidden = true;


            H113Constants.Token = token;

            var storyboard = UIStoryboard.FromName("Main", null);
            var vc = storyboard.InstantiateViewController("VideoCallViewController");
            NavigationController.PushViewController(vc, true);
        }
    }
}