// This file has been autogenerated from a class added in the UI designer.

using System;
using UIKit;

namespace WebRTC.iOS.Demo
{
    public partial class MainViewController : UIViewController
	{
		public MainViewController (IntPtr handle) : base (handle)
		{
		}


        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            AppRTCButton.TouchUpInside += (s, e) =>
            {
                var vc = new ConnectivityViewController();
                NavigationController.PushViewController(vc, true);
            };

            H113Button.TouchUpInside += (s, e) =>
            {
                var storyboard = UIStoryboard.FromName("Main", null);
                var vc = storyboard.InstantiateViewController("LoginViewController");
                NavigationController.PushViewController(vc, true);
            };
        }
    }
}
