// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using WebRTC.AppRTC;

namespace WebRTC.iOS.Demo
{
	public partial class MainViewController : UIViewController
	{
		public MainViewController (IntPtr handle) : base (handle)
		{
		}


        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            AppRTCButton.TouchUpInside += (s, e) =>
            {
                var vc = new AppRTCCallViewController(GenerateRoom.GenerateRoomName(), false);
                NavigationController.PushViewController(vc, true);
            };

            H113Button.TouchUpInside += (s, e) =>
            {
                var storyboard = UIStoryboard.FromName("Main", null);
                var vc = storyboard.InstantiateViewController("LoginViewController");
                NavigationController.PushViewController(vc, true);
            };
        }
    }
}
